---
abstract: 'An ORMish amalgamation.'
author:
  - 'Aran Deltac <bluefeet@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.101040'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Meld
recommends: {}
requires:
  DBIx::Connector: 0.33
  Moose: 1.01
  MooseX::Types: 0.21
  SQL::Astract: 1.65
  namespace::autoclean: 0.09
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=DBIx-Meld
version: 0.01
